# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julianny Favinha Donda
email: julianny.favinha@gmail.com
description: Add description here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
linkedin_URL: https://www.linkedin.com/in/julianny-favinha-donda-102a3b149/
github_username: julianny-favinha
twitter_username: 
facebook_URL: https://www.facebook.com/julianny.favinha
instagram_username: 
dribbble_username: 
500px_username: 
phone: 

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
